### ISSUE TITLE
Document parser issue with angled bracket links

### ISSUE THREAD

**Issue by amitness** [huggingface/doc-builder#58]
Currently, some of the links that are added to the source file in the format `<http://example.com/>` are broken when rendered on the docs. The links when clicked, have an extra `>` added to the end and thus result in a broken link.

Example: 
[Roformer Docs](https://huggingface.co/docs/transformers/model_doc/roformer#transformers.RoFormerTokenizer)
![image](https://user-images.githubusercontent.com/8587189/146226706-8da09bc8-4946-4565-bb46-60bc1761fea9.png)

The above link point to `https://pypi.org/project/rjieba/>` instead of `https://pypi.org/project/rjieba/`.

The same issue can be seen in the following links:
- The text `https://arxiv.org/abs/2008.00401%3E` in [mbart](https://huggingface.co/docs/transformers/model_doc/mbart#overview-of-mbart50)
- The text `https://github.com/pytorch/fairseq/tree/master/examples/wmt19%3E` in [fsmt](https://huggingface.co/docs/transformers/model_doc/fsmt)
- The text `https://huggingface.co/>` in [model_sharing](https://huggingface.co/docs/transformers/model_sharing#preparation)

and so on.

**Comment by sgugger** [comment]
Thanks for flagging this!
It looks like those links are not in the proper rst format and they weren't working in the older version of the doc either (one of the reason we are migrating, the rst syntax is so hard many people make mistakes). For instance see the one you point in model sharing in the [older doc](https://huggingface.co/transformers/v4.12.5/model_sharing.html#preparation)

In all those cases a `__` is missing after the `>`. Do you want to make a PR in Transformers to fix those? Otherwise we'll fix them on our side when we convert the corresponding source files/docstrings in Markdown.

**Comment by amitness** [comment]
@sgugger If it's being currently being ported to markdown then, I'd wait. Keeping this issue open for reference.

**Comment by sgugger** [comment]
I hunted for all of those links yesterday so I think they should all be fixed. Please let us know if you find another one!
